theme: jekyll-theme-minimal
title: 💻 📈 📊 📄
Description: fjmcgivney@gmail.com

[I'm an inline-style link](https://www.google.com)
 <a href="https://google.com" target="_blank">click to open the extarnal tab</a>

